
# -----------------------------

# Method1: network :

# docker network create redis
# docker build -t compose-flask .                             // create image from Dockerfile of project
# docker run -p 6379:6379 --network=redis redis               // create container from redis linked to network
# docker run -d -p 5009:5000 --network=redis compose-flask   // create container from own image and linked to network 


# Method2: compose.yaml: WITOUT VOLUME & ENV variable

# docker compose up 

# -----------------------------
# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#   redis:
#     image: "redis:alpine"


# ----------------------------------------------

# Method 3: compose.yaml: with VOLUME & ENV variable
# docker compose up 

services:
  web:
    depends_on:
      - redis
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
    volumes:
      - .:/data




